### ISSUE TITLE
lang

### ISSUE THREAD

**Issue by DariusKing** [Klnsyf-Sun/Battle-Royale#1]
hi bro!, i can help you translating your plugin to spanish
i'm from mexico and i wish, use your plugin, on my server, can i do it?

**Comment by Klnsyf-Sun** [comment]
Hi!
**Sure**, you can use this plugin on your server, but there are still **many bugs** in the plugin that are **still not fixed**.
In addition, **localization** support may need to wait for the **next version** (expected to be released in **two weeks**).

**Comment by DariusKing** [comment]
Thanks man, if i detect some bugs, i'm going to report here bro.
