### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by DariusKing** [Klnsyf-Sun/Battle-Royale#3]
hi men, i'm still now making the language file to spanish and portuguese to help you with your plugin, i see your snapshots, and i want to question if your plugin support multi-arenas or if the plugin can run on a server with other playing games or need to be the unique gamemode plugin, thanks for your work, the plugin is growing very fast and now have a lot of cool features, this have a very great potential, thanks bro.
i'm still installing to see how can run it, if i find some bugs i tell you here

**Comment by Klnsyf-Sun** [comment]
Hi. Thanks for your support.
In the current version, **each battlefield corresponds to a world**. Once you open a battlefield in a world, the plugin will affect nearly **all events** in the world. Therefore, it is **not advisable** to conduct other activities in a world which is a battlefield. However, the plugin does not affect **any world** which isn't a battlefield.
So, if you use **multi-world** on your server, you can use some of those worlds for **[Battle Royale]** and the other for other games.

**Comment by Klnsyf-Sun** [comment]
A great idea, I have already add this to my **TODO** list.
